<?php 
    $item = $block->getEditRecord();
    $urlImage = $block->_storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
    $image = $urlImage . 'product/index/' . $item[0]['images'];
?>
<div class="product-detail">
    <h2><?php echo $item[0]['title'] ?></h2>
    <img src="<?php echo $image?>" width="240" alt="product">
    <p>Price:<?php echo $item[0]['price'] ?> </p>
    <span>Content:<?php echo $item[0]['content'] ?><br/></span>
   
</div>